import Head from 'next/head'
import HomeCards from '../components/home/HomeCards'
import FreeShipping from '../components/Layout/FreeShipping'
import Layout from '../components/Layout/Layout'
import YourName from '../components/home/YourName'
import Connect from '../components/home/Connect'
import InstaFeed from '../components/home/InstaFeed'
import Header from '../components/home/Header'
import MobileYourName from '../components/home/MobileYourName'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home - gtex uniforms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Layout>
          <FreeShipping />
          <Header />
          <HomeCards marginTop={'mt-[40px]'}/>
          <HomeCards reverse={'flex-row-reverse'} mt={'lg:-mt-[6px]'} />
          <HomeCards mt={'lg:-mt-[6px]'} pb={'pb-[40px]'} />
          <YourName />
          <MobileYourName />
          <InstaFeed />
          <Connect />
        </Layout>
      </>
    </div>
  )
}
